# Generated by Django 4.2 on 2023-05-17 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('feature', models.CharField(max_length=100)),
                ('face_id', models.CharField(max_length=100)),
            ],
        ),
    ]
