# Generated by Django 4.2 on 2023-05-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='face_user',
            name='face_id_12',
            field=models.IntegerField(null=True),
        ),
    ]
