# Generated by Django 4.2 on 2023-05-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_face_user_face_id_12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face_user',
            name='face_id_12',
            field=models.IntegerField(default=0, verbose_name=11),
            preserve_default=False,
        ),
    ]
