# Generated by Django 4.2 on 2023-05-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_face_user_face_id_12'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='face_user',
            name='face_id_12',
        ),
    ]
