# Generated by Django 4.2 on 2023-05-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_face_user_face_id_12'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face_record',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('face_id', models.IntegerField()),
                ('in_type', models.IntegerField()),
                ('in_date_time', models.DateTimeField()),
                ('out_type', models.IntegerField()),
                ('out_date_time', models.DateTimeField()),
            ],
        ),
    ]
